"""encrypt tokens as text

Revision ID: c5bdfbba2c9a
Revises: 8c710e86b93e
Create Date: 2026-07-16 14:00:31.862551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5bdfbba2c9a'
down_revision: Union[str, Sequence[str], None] = '8c710e86b93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider_accounts', 'access_token',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('provider_accounts', 'refresh_token',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider_accounts', 'refresh_token',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=True,
               postgresql_using="convert_to(refresh_token, 'UTF8')",)
    op.alter_column('provider_accounts', 'access_token',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=False,
               postgresql_using="convert_to(access_token, 'UTF8')")
    # ### end Alembic commands ###
