"""add need reauth

Revision ID: f4c9a7b7f59c
Revises: c5bdfbba2c9a
Create Date: 2026-07-22 23:45:50.213705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c9a7b7f59c'
down_revision: Union[str, Sequence[str], None] = 'c5bdfbba2c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_accounts', sa.Column('needs_reauth', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_accounts', 'needs_reauth')
    # ### end Alembic commands ###
