"""create users and provider_accounts

Revision ID: 8c710e86b93e
Revises: 
Create Date: 2026-07-15 23:18:31.914844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c710e86b93e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('provider_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('google', name='provider_name'), nullable=False),
    sa.Column('provider_account_id', sa.String(length=300), nullable=False),
    sa.Column('account_email', sa.String(length=300), nullable=False),
    sa.Column('access_token', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token', sa.LargeBinary(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String(length=500)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_provider_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_accounts')),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_provider_accounts_provider_provider_account_id')
    )
    op.create_index(op.f('ix_provider_accounts_user_id'), 'provider_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_accounts_user_id'), table_name='provider_accounts')
    op.drop_table('provider_accounts')
    op.drop_table('users')
    # Make sure they enum type is also removed 
    op.execute('DROP TYPE provider_name')
    # ### end Alembic commands ###
